/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OpenlabButton {
    }
    interface TermTypist {
        "freezeUntilClick": () => Promise<void>;
        "playbook": { config: {}; plays: { context: string; input: string; output: string[]; emptybefore: boolean; pauseafter: boolean; }[]; };
        "unfreeze": () => Promise<void>;
    }
}
declare global {
    interface HTMLOpenlabButtonElement extends Components.OpenlabButton, HTMLStencilElement {
    }
    var HTMLOpenlabButtonElement: {
        prototype: HTMLOpenlabButtonElement;
        new (): HTMLOpenlabButtonElement;
    };
    interface HTMLTermTypistElement extends Components.TermTypist, HTMLStencilElement {
    }
    var HTMLTermTypistElement: {
        prototype: HTMLTermTypistElement;
        new (): HTMLTermTypistElement;
    };
    interface HTMLElementTagNameMap {
        "openlab-button": HTMLOpenlabButtonElement;
        "term-typist": HTMLTermTypistElement;
    }
}
declare namespace LocalJSX {
    interface OpenlabButton {
    }
    interface TermTypist {
        "playbook"?: { config: {}; plays: { context: string; input: string; output: string[]; emptybefore: boolean; pauseafter: boolean; }[]; };
    }
    interface IntrinsicElements {
        "openlab-button": OpenlabButton;
        "term-typist": TermTypist;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "openlab-button": LocalJSX.OpenlabButton & JSXBase.HTMLAttributes<HTMLOpenlabButtonElement>;
            "term-typist": LocalJSX.TermTypist & JSXBase.HTMLAttributes<HTMLTermTypistElement>;
        }
    }
}
